  _productshare:
    pattern:  /
    defaults: { _controller: ProductShareBundle:Default:index }

productshare_test_hello:
    pattern:  /{name}
    defaults: { _controller: ProductShareBundle:Default:hello }
